export const TIMEZONES = [
  // Americas
  { city: 'New York', country: 'United States', countryCode: 'US', timezone: 'America/New_York' },
  { city: 'Los Angeles', country: 'United States', countryCode: 'US', timezone: 'America/Los_Angeles' },
  { city: 'Chicago', country: 'United States', countryCode: 'US', timezone: 'America/Chicago' },
  { city: 'Denver', country: 'United States', countryCode: 'US', timezone: 'America/Denver' },
  { city: 'Toronto', country: 'Canada', countryCode: 'CA', timezone: 'America/Toronto' },
  { city: 'Vancouver', country: 'Canada', countryCode: 'CA', timezone: 'America/Vancouver' },
  { city: 'Mexico City', country: 'Mexico', countryCode: 'MX', timezone: 'America/Mexico_City' },
  { city: 'São Paulo', country: 'Brazil', countryCode: 'BR', timezone: 'America/Sao_Paulo' },
  { city: 'Buenos Aires', country: 'Argentina', countryCode: 'AR', timezone: 'America/Argentina/Buenos_Aires' },
  { city: 'Santiago', country: 'Chile', countryCode: 'CL', timezone: 'America/Santiago' },
  { city: 'Lima', country: 'Peru', countryCode: 'PE', timezone: 'America/Lima' },
  { city: 'Bogotá', country: 'Colombia', countryCode: 'CO', timezone: 'America/Bogota' },

  // Europe
  { city: 'London', country: 'United Kingdom', countryCode: 'GB', timezone: 'Europe/London' },
  { city: 'Paris', country: 'France', countryCode: 'FR', timezone: 'Europe/Paris' },
  { city: 'Berlin', country: 'Germany', countryCode: 'DE', timezone: 'Europe/Berlin' },
  { city: 'Madrid', country: 'Spain', countryCode: 'ES', timezone: 'Europe/Madrid' },
  { city: 'Rome', country: 'Italy', countryCode: 'IT', timezone: 'Europe/Rome' },
  { city: 'Amsterdam', country: 'Netherlands', countryCode: 'NL', timezone: 'Europe/Amsterdam' },
  { city: 'Brussels', country: 'Belgium', countryCode: 'BE', timezone: 'Europe/Brussels' },
  { city: 'Vienna', country: 'Austria', countryCode: 'AT', timezone: 'Europe/Vienna' },
  { city: 'Stockholm', country: 'Sweden', countryCode: 'SE', timezone: 'Europe/Stockholm' },
  { city: 'Oslo', country: 'Norway', countryCode: 'NO', timezone: 'Europe/Oslo' },
  { city: 'Copenhagen', country: 'Denmark', countryCode: 'DK', timezone: 'Europe/Copenhagen' },
  { city: 'Helsinki', country: 'Finland', countryCode: 'FI', timezone: 'Europe/Helsinki' },
  { city: 'Warsaw', country: 'Poland', countryCode: 'PL', timezone: 'Europe/Warsaw' },
  { city: 'Prague', country: 'Czech Republic', countryCode: 'CZ', timezone: 'Europe/Prague' },
  { city: 'Budapest', country: 'Hungary', countryCode: 'HU', timezone: 'Europe/Budapest' },
  { city: 'Athens', country: 'Greece', countryCode: 'GR', timezone: 'Europe/Athens' },
  { city: 'Lisbon', country: 'Portugal', countryCode: 'PT', timezone: 'Europe/Lisbon' },
  { city: 'Dublin', country: 'Ireland', countryCode: 'IE', timezone: 'Europe/Dublin' },
  { city: 'Moscow', country: 'Russia', countryCode: 'RU', timezone: 'Europe/Moscow' },
  { city: 'Istanbul', country: 'Turkey', countryCode: 'TR', timezone: 'Europe/Istanbul' },

  // Asia
  { city: 'Tokyo', country: 'Japan', countryCode: 'JP', timezone: 'Asia/Tokyo' },
  { city: 'Seoul', country: 'South Korea', countryCode: 'KR', timezone: 'Asia/Seoul' },
  { city: 'Beijing', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai' },
  { city: 'Shanghai', country: 'China', countryCode: 'CN', timezone: 'Asia/Shanghai' },
  { city: 'Hong Kong', country: 'Hong Kong', countryCode: 'HK', timezone: 'Asia/Hong_Kong' },
  { city: 'Singapore', country: 'Singapore', countryCode: 'SG', timezone: 'Asia/Singapore' },
  { city: 'Bangkok', country: 'Thailand', countryCode: 'TH', timezone: 'Asia/Bangkok' },
  { city: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'MY', timezone: 'Asia/Kuala_Lumpur' },
  { city: 'Jakarta', country: 'Indonesia', countryCode: 'ID', timezone: 'Asia/Jakarta' },
  { city: 'Manila', country: 'Philippines', countryCode: 'PH', timezone: 'Asia/Manila' },
  { city: 'Ho Chi Minh City', country: 'Vietnam', countryCode: 'VN', timezone: 'Asia/Ho_Chi_Minh' },
  { city: 'Mumbai', country: 'India', countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { city: 'Delhi', country: 'India', countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { city: 'Bangalore', country: 'India', countryCode: 'IN', timezone: 'Asia/Kolkata' },
  { city: 'Dubai', country: 'United Arab Emirates', countryCode: 'AE', timezone: 'Asia/Dubai' },
  { city: 'Tel Aviv', country: 'Israel', countryCode: 'IL', timezone: 'Asia/Jerusalem' },
  { city: 'Riyadh', country: 'Saudi Arabia', countryCode: 'SA', timezone: 'Asia/Riyadh' },
  { city: 'Karachi', country: 'Pakistan', countryCode: 'PK', timezone: 'Asia/Karachi' },
  { city: 'Dhaka', country: 'Bangladesh', countryCode: 'BD', timezone: 'Asia/Dhaka' },

  // Oceania
  { city: 'Sydney', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Sydney' },
  { city: 'Melbourne', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Melbourne' },
  { city: 'Brisbane', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Brisbane' },
  { city: 'Perth', country: 'Australia', countryCode: 'AU', timezone: 'Australia/Perth' },
  { city: 'Auckland', country: 'New Zealand', countryCode: 'NZ', timezone: 'Pacific/Auckland' },
  { city: 'Wellington', country: 'New Zealand', countryCode: 'NZ', timezone: 'Pacific/Auckland' },

  // Africa
  { city: 'Cairo', country: 'Egypt', countryCode: 'EG', timezone: 'Africa/Cairo' },
  { city: 'Johannesburg', country: 'South Africa', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
  { city: 'Lagos', country: 'Nigeria', countryCode: 'NG', timezone: 'Africa/Lagos' },
  { city: 'Nairobi', country: 'Kenya', countryCode: 'KE', timezone: 'Africa/Nairobi' },
  { city: 'Casablanca', country: 'Morocco', countryCode: 'MA', timezone: 'Africa/Casablanca' },
];
